server:
  port: 0

spring:
  application:
    name: tb-statistic-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/tasks_book"
    username: "postgres"
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tasksbook
          jwk-set-uri: http://localhost:8080/realms/tasksbook/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"